move_spd = 1;
min_move_speed = 1;
target = noone; //which node to move to
//moving = false; //
look_time = 0; //how long the npc will stop and look at the node
happiness = 0;
leaving_park = false;
color = choose(7,10,12) * 60;
alarm[0] = 1;
alarm[1] = -1;